package com.xyb.entity;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuser.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuser.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuser.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuser.usertype
     *
     * @mbggenerated
     */
    private String usertype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuser.id
     *
     * @return the value of wuser.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuser.id
     *
     * @param id the value for wuser.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuser.username
     *
     * @return the value of wuser.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuser.username
     *
     * @param username the value for wuser.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuser.password
     *
     * @return the value of wuser.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuser.password
     *
     * @param password the value for wuser.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuser.usertype
     *
     * @return the value of wuser.usertype
     *
     * @mbggenerated
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuser.usertype
     *
     * @param usertype the value for wuser.usertype
     *
     * @mbggenerated
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }
}